# Etapa 1: Instalación de dependencias que rara vez cambian
FROM python:3.8-bullseye
ENV FLASK_APP=app
EXPOSE 80 443 27017
LABEL maintainer="agustincarranza@mi.unc.edu.ar, fd.dandrea@unc.edu.ar"
RUN apt-get update && \
    apt-get install -y ffmpeg libsm6 libxext6 && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir "/app"
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt